//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YumYum
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int Id { get; set; }
        public decimal HourlyRate { get; set; }
        public System.DateTime HireDate { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual StaffPosition StaffPosition { get; set; }
    }
}
