//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YumYum
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffPosition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffPosition()
        {
            this.WorkingRosters = new HashSet<WorkingRoster>();
        }
    
        public int StaffPositionId { get; set; }
        public string Position { get; set; }
        public int StaffTypeId { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual StaffType StaffType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkingRoster> WorkingRosters { get; set; }
    }
}
