//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YumYum
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingRoster
    {
        public int RosterId { get; set; }
        public int StaffId { get; set; }
        public int PositionId { get; set; }
        public int ShiftId { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual StaffPosition StaffPosition { get; set; }
        public virtual WorkingShift WorkingShift { get; set; }
    }
}
